#!/bin/bash
# Creates include/secrets.h (ignored by git) from an older checkout whose
# include/app_config.h still has the real Wi-Fi and bridge values inline.
# The values are copied as they are and never printed.
#
#   tools/import-legacy-secrets.sh <old include/app_config.h> [--force]
#
# Afterwards it tells you which bridge host the board will poll and whether
# the board's token matches ~/.codex-pet-bridge/token (the bridge's token).
set -euo pipefail

FW="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$FW/include/secrets.h"
SRC="${1:-}"
FORCE="${2:-}"

if [[ -z "$SRC" || "$SRC" == "-h" || "$SRC" == "--help" ]]; then
  sed -n '2,9p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 2
fi
[[ -f "$SRC" ]] || { echo "not found: $SRC" >&2; exit 1; }
if [[ "$(cd "$(dirname "$SRC")" && pwd)/$(basename "$SRC")" == "$FW/include/app_config.h" ]]; then
  echo "that is this checkout's own app_config.h; point at the old checkout's copy" >&2
  exit 1
fi

python3 - "$SRC" "$DEST" "$FORCE" "$HOME/.codex-pet-bridge/token" <<'PY'
import os
import re
import sys
from urllib.parse import parse_qs, urlsplit

src, dest, force, token_file = sys.argv[1:5]
text = open(src, encoding="utf-8").read()
names = ("kWifiSsid", "kWifiPassword", "kBridgeUrl")
found = {}
for name in names:
    match = re.search(
        r'static\s+constexpr\s+const\s+char\s*\*\s*' + name + r'\s*=\s*((?:\s*"(?:[^"\\]|\\.)*")+)\s*;',
        text,
    )
    if not match:
        sys.exit(f"{name} not found in {src}")
    literal = " ".join(match.group(1).split())
    value = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', literal))
    if not value or "YOUR_" in value or "<" in value:
        sys.exit(f"{name} in {src} is still a placeholder")
    found[name] = (literal, value)

if os.path.exists(dest) and force != "--force":
    sys.exit(f"{dest} already exists (add --force to replace it)")

lines = [
    "#pragma once",
    "",
    "// Generated by tools/import-legacy-secrets.sh. Git ignores this file.",
    "",
]
for name in names:
    lines.append(f"static constexpr const char* {name} =")
    lines.append(f"    {found[name][0]};")
fd = os.open(dest, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")
os.chmod(dest, 0o600)

url = urlsplit(found["kBridgeUrl"][1])
print(f"wrote {dest} (values not shown)")
print(f"  the board will poll {url.hostname}:{url.port or 80}{url.path}")
token = parse_qs(url.query).get("token", [""])[0]
if not token:
    print("  WARNING: the bridge URL has no token; a bridge with a token will answer 401")
elif os.path.exists(token_file):
    bridge_token = open(token_file, encoding="utf-8").read().strip()
    if token == bridge_token:
        print("  token matches ~/.codex-pet-bridge/token")
    else:
        print("  WARNING: token differs from ~/.codex-pet-bridge/token; the board would get 401")
else:
    print("  (no ~/.codex-pet-bridge/token yet; the bridge installer creates it from the old LaunchAgent)")
PY
