#!/bin/bash
# Creates include/secrets.h (ignored by git) for a fresh setup.
#
#   tools/make-secrets.sh [--ip 192.168.1.23] [--port 17366] [--force]
#
# Asks for the Wi-Fi name and password (the ESP32-S3 only joins 2.4 GHz
# networks) and builds the bridge URL from this Mac's LAN address and the
# bridge token in ~/.codex-pet-bridge/token (created by the bridge installer).
# Nothing secret is printed. Give the Mac a fixed LAN address (a DHCP
# reservation on the router): the address is compiled into the firmware.
set -euo pipefail

FW="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$FW/include/secrets.h"
TOKEN_FILE="${PET_BRIDGE_TOKEN_FILE:-$HOME/.codex-pet-bridge/token}"
IP=""
PORT=17366
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ip) IP="${2:-}"; shift ;;
    --port) PORT="${2:-}"; shift ;;
    --force) FORCE=1 ;;
    -h|--help) sed -n '2,11p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

die() { echo "error: $*" >&2; exit 1; }

[[ -s "$TOKEN_FILE" ]] || die "no bridge token at $TOKEN_FILE; install the bridge first (bridge/codex-pet-bridge/tools/mac/install.sh --apply)"
if [[ -z "$IP" ]] && command -v ipconfig >/dev/null 2>&1; then
  IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
fi
[[ -n "$IP" ]] || die "could not find this Mac's LAN address; pass --ip"
[[ "$PORT" =~ ^[0-9]+$ ]] || die "bad port: $PORT"
if [[ -e "$DEST" && "$FORCE" != 1 ]]; then
  die "$DEST already exists (add --force to replace it)"
fi

read -r -p "Wi-Fi name (2.4 GHz): " SSID
read -r -s -p "Wi-Fi password: " PASSWORD
echo
[[ -n "$SSID" ]] || die "the Wi-Fi name is empty"

PET_SSID="$SSID" PET_PASSWORD="$PASSWORD" PET_URL="http://$IP:$PORT/esp32/poll?token=$(tr -d '[:space:]' < "$TOKEN_FILE")" \
  python3 - "$DEST" <<'PY'
import os
import sys

def literal(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

dest = sys.argv[1]
text = "\n".join([
    "#pragma once",
    "",
    "// Generated by tools/make-secrets.sh. Git ignores this file.",
    "",
    f"static constexpr const char* kWifiSsid = {literal(os.environ['PET_SSID'])};",
    f"static constexpr const char* kWifiPassword = {literal(os.environ['PET_PASSWORD'])};",
    "static constexpr const char* kBridgeUrl =",
    f"    {literal(os.environ['PET_URL'])};",
    "",
])
fd = os.open(dest, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, "w", encoding="utf-8") as handle:
    handle.write(text)
os.chmod(dest, 0o600)
PY

echo "wrote $DEST (values not shown)"
echo "  the board will poll http://$IP:$PORT/esp32/poll with the bridge token"
